[build]
  command = "npm run build"
  publish = "dist/data-obsfucation/browser"

[build.environment]
  NODE_VERSION = "18"

# This section proxies requests to your API to avoid CORS errors
[[redirects]]
  from = "/api/*"
  to = "https://ria-chat-gateway-production.up.railway.app/:splat"
  status = 200
  force = true